package play.modules.cmscore.annotations;

public enum DecorateType {

    META, SCRIPT, TITLE, BODY,

    LIST_BULLET, LIST_ORDERED,

    FORM, INPUT_HIDDEN, INPUT_TEXT, INPUT_TEXTAREA, INPUT_RADIO_BUTTON, INPUT_BUTTON, INPUT_SUBMIT, INPUT_RESET, INPUT_IMAGE, INPUT_PASSWORD,

    PANEL
    
}
